/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/football.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={0.17} castShadow>
      <mesh geometry={nodes.Icosphere_1.geometry} material={materials.white} />
      <mesh geometry={nodes.Icosphere_2.geometry} material={materials.black} />
    </group>
  )
}

useGLTF.preload('/football.glb')
