/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/footballplayerblue.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorig5Hips} />
        <skinnedMesh geometry={nodes.Ch38_Body.geometry} material={materials.Ch38_body} skeleton={nodes.Ch38_Body.skeleton} />
        <skinnedMesh geometry={nodes.Ch38_Eyelashes.geometry} material={materials.Ch38_hair} skeleton={nodes.Ch38_Eyelashes.skeleton} />
        <skinnedMesh geometry={nodes.Ch38_Hair.geometry} material={materials.Ch38_hair} skeleton={nodes.Ch38_Hair.skeleton} />
        <skinnedMesh geometry={nodes.Ch38_Shirt.geometry} material={materials.Material} skeleton={nodes.Ch38_Shirt.skeleton} />
        <skinnedMesh geometry={nodes.Ch38_Shoes.geometry} material={materials.Ch38_body} skeleton={nodes.Ch38_Shoes.skeleton} />
        <skinnedMesh geometry={nodes.Ch38_Shorts.geometry} material={materials.Ch38_body} skeleton={nodes.Ch38_Shorts.skeleton} />
        <skinnedMesh geometry={nodes.Ch38_Socks.geometry} material={materials.Ch38_body} skeleton={nodes.Ch38_Socks.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/footballplayerblue.glb')
